project:
  type: website

website:
  title: "eimhin.co"
  navbar:
    right:
      - notes.qmd
      - text: LinkedIn
        href: https://www.linkedin.com/in/eimhin-rafferty/
      - text: Github
        href: https://github.com/eimhinr
      - text: Strava
        href: https://www.strava.com/athletes/15882927
      - text: Instagram
        href: https://www.instagram.com/eimhinr/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

