
project:
  type: website

website:
  title: "eimhin-co"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: article
    css: styles.css
    theme: cosmo
    linestretch: 1.2
    margin-top: 1in
    margin-bottom: 1in
    margin-left: 1in
    margin-right: 1in
    toc: false
    # toc-depth: 2
    keep_tex: true
    include-in-header:
      text: |
        \usepackage{fontspec}
        \setmainfont{Arial}
        \usepackage{titlesec}
        \titlespacing\section{1.5pt}{*0}{*0}
        \titlespacing\subsection{1.5pt}{*0}{*0}
        \titlespacing\subsubsection{1.5pt}{*0}{*0}