---
title: "Eimhin Rafferty"
output:
  html:
    theme: cosmo
  pdf:
    theme: cosmo
    documentclass: article
    mainfont: Arial
--- 
<!-- # Eimhin Rafferty -->
Lecco, Italy • +393792058117 • eimhin@pm.me • [eimhin.co](http://www.eimhin.co) • [linkedin/eimhin](https://www.linkedin.com/in/eimhin-rafferty)

## Professional Experience

### Archilogic • Product Manager • *11/2022 - 05/2024*  

- Managed product roadmap for Editor, Data Services, and Customer Onboarding verticals. Defined, gathered and analyzeed metrics to drive decision-making and inform OKRs.
- Led product feature discovery, requirements gathering, and authored PRDs to drive product development. Collaborated with Sales, Customer Support, and other product teams to balance growth features and core product development.
- Delivered new planar graph data structure and compatible Editor 4.0 modelling platform. Supported users with advanced tools, resulting in a 2.5x increase in data conversion quality and a 1.8x reduction in conversion times.
- Conducted daily standups and weekly backlog refinement calls to ensure alignment and progress within the remote first, agile team in 2 week cycles over rolling 6 committed backlog week cycles.
- - Weekly reviews with customer support team to support being the voice of the customer in product team. Listended in on CS calls and supported CS workflows. 
- Provided sales demos, customer support, and onboarding, supporting business activities.

### WeWork • Product Manager, Design Technology • *07/2018 - 12/2022*

- Led the technical aspects of the "Record Model Initiative," a $2.7M project to deliver uniform, verified real estate data, significantly informing key business metrics.
- Established ring-fenced support workflows and set up a support team to manage updates, accurately maintaining critical business data verified by the Record Model Initiative, ensuring that teams could trust the reliability of their data.
- Conducted RSF SKU Pricing Analysis, designing and validating a new pricing model using a dataset of 130k inventory rooms and 100k inventory items.
- Stood up and managed the Design Technology support ticketing system, moving all support from ad hoc direct contact to the Jira platform. Increased trust, accountability, and reporting to best in class.
- Managed design software and workflows, serving as Contract Administrator for $3M in Autodesk services and software.
- Re-engineered processes for Design Studios, reducing sales and pre-con collateral production time from 2.5 days to 2 hours, impacting 70% of EMEA sales. Provided direct support and traning to teams using these workflows. 
- Developed and maintained documentation, training content, and tools for internal and external teams to deliver accurate design information. Supported this with bespoke plugins and utilities to streamline productivity and quality control, integrating with third-party applications.
- Built strong working relationships across Technology, Sales, Operations, and Finance organisations, advocating for the needs of real estate data integrity and supporting sales and operations strategies.

### Pascall + Watson • Building Information Model Coordinator • *11/2016 - 07/2018*

- Responsible for planning, maintaining and enforcing the 'Project Building Information Model Execution Plan' (BEP) for £480M Airport Campus Development Project. Implemented BS 1192 standards on the project across multiple parties.
- Developed and Implemented new technology processes to increase efficacy and accuracy, including: Reduced biweekly design freeze from 72hrs to 8hrs & deliverable set production time from 4hrs to 20 mins.
- Point of contact for traning and support for Internal and External teams in their speciailsed software. Enforced compliance with contract document reuqirements. 

### Watkins Gray International • Building Information Model Manager • *02/2014 - 11/2016*

- Responsible for practice wide building information management and digital contract documents on projects from concept through to construction in education, healthcare and residential sectors.
- Served on a technical advisory group for a shared professional indemnity insurance group, providing expertise on BIM and design technology in practice.

### 1508 London • Architectural Technologist • *11/2012 - 02/2014*

- Technical lead on luxury interiors and complex historical urban projects

### B+R Architects • Architectural Technologist • *08/2010 - 11/2012*

- Project Architectural technology lead and BIM specialist.

## Education

**BSc (Hons) in Architectural Technology** 
Technological University Dublin *09/2005 - 05/2010*

## Skills

- **Technical Skills**: Product Lifecycle Management, Market Research, Agile Methodologies, Project Management, Data Analysis, Product Roadmapping, User Experience (UX) Design, Wireframing and Prototyping, Customer Support, Customer Enablement 
- **Soft Skills**: Communication, Leadership, Strategic Thinking, Problem-Solving, Customer Focus, Decision-Making, Collaboration
- **Tools and Software**: Python, SQL, Typescript, Jira, Linear, Figma, Monday.com, Miro, Lucidchart, Lookback, Google Analytics, Mixpanel, HubSpot, Slack, Excel, Postman, Notion, Retool
